dist: xenial

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.11.2-xenial
  - sudo apt-get update -qq
 
install:
  - sudo apt-get install -qq g++-6
  - sudo apt-get --yes install qt511-meta-minimal
  - sudo apt-get --yes install qt511websockets
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - sudo apt-get install libi2c-dev

before_script:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT
  - mkdir external
  - cd external
  - git submodule add -f https://github.com/gabime/spdlog.git
  - git submodule update --init
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
